# Specify the number of open pull requests allowed

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
      - "backend"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
      - "frontend"
    open-pull-requests-limit: 10