#https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
#You can use the branches or branches-ignore filter to configure your workflow to only run on pull requests that target specific branches. For more information, see "Workflow syntax for GitHub Actions."
#consider this action: https://github.com/marketplace/actions/find-current-pull-request

#ignore readme updates
#check if you can pass in variables to the ignore section

name: 'Check PRs'
# https://github.com/hrvey/combine-prs-workflow
# Controls when the action will run - in this case triggered manually
on:
  workflow_dispatch:
    inputs:
      tbd:
        description: 'Branch prefix to find combinable PRs based on'
        required: true
        default: 'dependabot'
  pull

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #https://docs.github.com/en/rest/reference/pulls#reviews
      - name: Get pull request number
        run: echo 'The number is ${{ github.event.number }}'
        
      - uses: actions/github-script@v3
        id: fetch-branch-names
        name: Fetch branch names
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(${{ github.event.number }});
            const pulls = await github.paginate('GET /repos/:owner/:repo/pulls/${{ github.event.number }}/requested_reviewers', {
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(${{ github.event.number }});
            
