#https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
#You can use the branches or branches-ignore filter to configure your workflow to only run on pull requests that target specific branches. For more information, see "Workflow syntax for GitHub Actions."
#consider this action: https://github.com/marketplace/actions/find-current-pull-request

#ignore readme updates
#check if you can pass in variables to the ignore section

name: 'Check PRs'
# https://github.com/hrvey/combine-prs-workflow
# Controls when the action will run - in this case triggered manually
on:
  workflow_dispatch:
    inputs:
      tbd:
        description: 'Branch prefix to find combinable PRs based on'
        required: true
        default: 'dependabot'
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  pull_request:
    types: [opened, labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-prs:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name != 'comments' }}
    # sequence of tasks that will be executed as part of the job
    steps:
      #https://docs.github.com/en/rest/reference/pulls#reviews
      - name: Get pull request number
        run: echo 'The number is ${{ github.event.number }}'
        
      - name: Fetch reviewer names
        uses: actions/github-script@v3
        id: fetch-reviewer-names
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          # hold: 'GET /repos/:owner/:repo/pulls/:pull_number/requested_reviewers'
          # https://stackoverflow.com/questions/11922383/how-can-i-access-and-process-nested-objects-arrays-or-json
          script: |
            console.log(${{ github.event.number }});
            const pulls = await github.paginate('GET /repos/:owner/:repo/pulls/:pull_number', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.number }}
            });
            body = ""
            title = ""
            reviewers = ""
            other = ""
            for (const pull of pulls) {
              body = pull['body']
              title = pull['user']['login']
              reviewers = pull['requested_reviewers']
              other = pull['head']['user']
            };
            console.log('See pull details: ', pulls);
            console.log('Body: ' + body);
            console.log('Title: ' + title);
            console.log('Requested reviewers: ' + reviewers);
            console.log('Other: ', other);
            
