name: Test site build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, labeled]

jobs:
  build:
    if: ${{ github.event.label.name == 'dependencies' }}
    runs-on: ubuntu-latest
    
    # identify array of node versions to run
    strategy:
      matrix:
        node: [12.x]
    
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: gh-pages-production
          
      - name: Cache node dependencies
        uses: actions/cache@v2.1.7
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/client/package.json') }}
    
      # Configures the node version used on GitHub-hosted runners
      - name: Set up Node JS
        uses: actions/setup-node@v3
        with:
          # The Node.js version to configure
          node-version: ${{ matrix.node }}
   
      - name: Install NPM and Test Build
        run: |
          cd client
          npm ci
          npm run build
